version: '3'

volumes:
  data:

services:
  kyouko:
    image: ghcr.io/slaxnetwork/kyouko:main
    build: .
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - /data:/var/lib/redis/data